# Generated by Django 4.1.2 on 2022-10-30 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasecart",
            name="purchase_order_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
