# Generated by Django 4.1.2 on 2022-10-30 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0003_purchasecart_purchase_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasecartproduct",
            name="purchase_cart",
        ),
        migrations.AddField(
            model_name="purchasecartproduct",
            name="user",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PurchaseCart",
        ),
    ]
