# Generated by Django 4.1.2 on 2022-10-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_user_type"),
        ("dashboard", "0004_remove_purchasecartproduct_purchase_cart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.supplier",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_payments",
            },
        ),
    ]
