# Generated by Django 4.1.2 on 2022-10-30 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0005_purchaseorder_is_paid_purchaseorder_order_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="user",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
