# Generated by Django 4.1.2 on 2022-10-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_purchaseorder_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="is_paid",
        ),
    ]
