# Generated by Django 4.1.2 on 2022-10-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_remove_purchaseorder_is_paid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="purchase_order_id",
            new_name="order_id",
        ),
    ]
