# Generated by Django 4.1.2 on 2022-10-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="unread",
            field=models.BooleanField(default=True),
        ),
    ]
