# Generated by Django 4.1.2 on 2022-11-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_product_buying_price"),
        ("dashboard", "0010_notification_unread"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.FloatField(default=0)),
            ],
            options={
                "db_table": "account_balance",
            },
        ),
        migrations.AlterField(
            model_name="purchasecartproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.product"
            ),
        ),
    ]
