# Generated by Django 4.1.2 on 2022-12-13 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_supplier_email"),
        ("dashboard", "0011_accountbalance_alter_purchasecartproduct_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.supplier",
            ),
        ),
    ]
