# Generated by Django 4.1.2 on 2022-10-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="office_location",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone",
            field=models.CharField(default="", max_length=13),
        ),
        migrations.AddField(
            model_name="supplier",
            name="store_location",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="supplier",
            name="website_url",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="payment_account",
            field=models.CharField(default="", max_length=80),
        ),
    ]
