# Generated by Django 4.1.2 on 2022-10-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_supplier_office_location_supplier_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="regitration_number",
            field=models.CharField(default="", max_length=100),
        ),
    ]
