# Generated by Django 4.1.2 on 2022-10-23 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_supplier_regitration_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
    ]
