# Generated by Django 4.1.2 on 2022-10-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplier",
            old_name="regitration_number",
            new_name="registration_number",
        ),
    ]
