# Generated by Django 4.1.2 on 2022-10-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_regitration_number_supplier_registration_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("SUPPLIER", "Supplier"),
                    ("RETAILER", "Retailer"),
                    ("CUSTOMER", "Customer"),
                ],
                default="CUSTOMER",
                max_length=10,
            ),
        ),
    ]
