# Generated by Django 4.1.2 on 2022-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_supplier_created_supplier_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png", upload_to="accounts/avatars"
            ),
        ),
    ]
