# Generated by Django 4.1.2 on 2022-11-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="company_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
