# Generated by Django 4.1.2 on 2022-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_supplier_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(default="supplier@mail.com", max_length=200),
            preserve_default=False,
        ),
    ]
