# Generated by Django 4.1.2 on 2022-10-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='categories',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
