# Generated by Django 4.1.2 on 2022-10-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
    ]
