# Generated by Django 4.1.2 on 2022-10-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity_sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
