# Generated by Django 4.1.2 on 2022-10-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_orderitem_item_alter_orderitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity_sold",
        ),
    ]
