# Generated by Django 4.1.2 on 2022-10-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_shippingaddress_county_productsupplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
