# Generated by Django 4.1.2 on 2022-10-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
