# Generated by Django 4.1.2 on 2022-10-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_product_notification_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="notification_sent",
        ),
    ]
