# Generated by Django 4.1.2 on 2022-11-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_product_notification_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="buying_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
