# Generated by Django 4.1.2 on 2022-11-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_product_buying_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="created",
        ),
        migrations.AddField(
            model_name="order",
            name="date_created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="time_created",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
