# Generated by Django 4.1.2 on 2022-11-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_remove_order_created_order_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsupplier",
            name="date_signed",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="productsupplier",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
